# Generated by Django 4.0.3 on 2022-03-18 09:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 9, 11, 27, 972558, tzinfo=utc))),
                ('interest', models.FloatField(default=0)),
                ('balance', models.FloatField(default=0)),
                ('interest_bool', models.BooleanField(default=True)),
                ('agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
