# Generated by Django 4.0.3 on 2022-03-20 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='date_debts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
